name: echemdb
channels:
  - conda-forge
  - defaults
dependencies:
  - astropy>=5,<6
  - black
  - filelock>=3,<4
  - frictionless>=5.5.0,<6
  - isort
  - jupytext>=1.13,<2
  - matplotlib-base>=3.5.0,<4
  - myst-nb>=0.13.0,<0.14.0
  - myst-parser>=0.15,<0.17
  - pandas>=1,<2
  - pip
  - plotly>=5,<6
  - pybtex>=0.24,<0.25
  - pylint
  - pytest
  - pytest-doctestplus
  - pytest-xdist
  - pytest-remotedata
  - python>=3.9
  - sphinx>=4.3,<5
  - svgdigitizer>=0.7.0,<0.8.0
  - pip:
    - linkchecker
    - sphinx_rtd_theme>=1,<2
