name: echemdb
channels:
  - conda-forge
  - defaults
dependencies:
  - astropy>=5,<6
  - black
  - filelock>=3,<4
  - frictionless>=4.31,<5
  - isort
  - jupytext
  - myst-nb>=0.13.0,<0.14.0
  - myst-parser>=0.15,<0.17
  - pandas>=1,<2
  - pip
  - plotly<=5,<6
  - pybtex>=0.24,<0.25
  - pylint
  - pytest
  - pytest-doctestplus
  - pytest-xdist
  - pytest-remotedata
  - sphinx>=4.3,<5
  - svgdigitizer>=0.5.0,<0.6.0
  - pip:
    - linkchecker
